codecov:
  notify:
    require_ci_to_pass: yes

# TODO - This does not want to work, ignoring in pom.xml for now
ignore:
  - "src/main/java/com/workiva/eva/clientservice/config"
  - "src/main/java/com/workiva/eva/clientservice/ClientServiceApplication.java"

coverage:
  precision: 0
  round: down
  range: "85...100"
  status:
    status:
      project:
        default:
          threshold: 2.5
      patch:
        default:
          threshold: 2.5
      changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, files, footer"
  behavior: default
  require_changes: no

