version: '3.6'
services:
# TODO - add eva-catalog / eva compose to this file and debug
  eva-client-service:
    image: ${SKYNET_APPLICATION_EVA_CLIENT_SERVICE:-drydock.workiva.net/workiva/eva-client-service:latest-release}
    depends_on:
      - eva-catalog
      - eva
    environment:
      - CATALOG_URL=http://eva-catalog:3000
      - LOGBACK_APPENDER=STDOUT
      - SANITIZE_EXCEPTIONS=false
      - TRACE_RECORDER=off
      - DISABLE_TELEMETRY=true
